### ISSUE TITLE
hello world example fails for me

### ISSUE THREAD

**Issue by truemagic-coder** [http-rs/tide-acme#1]
I tried the hello world example and rust-analyzer says the TideRustlsExt is not used and then gives this error: 

no method named `acme` found for struct `TlsListenerBuilder<_>` in the current scope
method not found in `TlsListenerBuilder<_>

Any help would be great - thanks!

**Comment by jbr** [comment]
Hi! You likely need to upgrade tide-rustls to 0.3

**Comment by truemagic-coder** [comment]
Thanks - it works!
