### ISSUE TITLE
Provide email address in example code

### ISSUE THREAD

**Issue by jsha** [http-rs/tide-acme#2]
Hi! Let's Encrypt engineer here. Could I ask you to make the example code in the README provide an email address, like `example@example.com`? Our experience with ACME clients has been that people don't go out of their way to configure an email address if it's not in the default, but if it is in the default, they're usually happy to provide it.

Providing the email address has a lot of advantages. The main one is that the user can get expiration emails, but also when clients are buggy and spam the service, we really make an effort to connect the user with the client developer so the bugs can be fixed. That starts with an email to the user. Also, we occasionally make breaking changes to our API and need to email our users about it.

If the example email domain is, e.g. `example.com`, [Boulder will reject it until the user provides a different email address](https://github.com/letsencrypt/boulder/blob/99344a1228ea295fad486501838b36500bab5de2/policy/pa.go#L297-L307).

**Comment by joshtriplett** [comment]
@jsha I'd be happy to do so. However, the underlying crate rustls-acme doesn't currently support providing a contact email address. Would you mind filing a similar issue on that crate? Once such support exists, I'd be happy to provide a binding for it. (If you think it'd be appropriate, I'd even be happy to *require* a contact email when using the production infrastructure.)

**Comment by jsha** [comment]
Done, thanks!

> (If you think it'd be appropriate, I'd even be happy to require a contact email when using the production infrastructure.)

The way Certbot does this is that you must provide either an email address, or the `--register-unsafely-without-email-address`. This has produced good results, in my opinion: almost always if there is a problem with a Certbot client, we are able to reach the user. And for people who really don't want to provide an address, they have that option and the risks are clear.

**Comment by joshtriplett** [comment]
@jsha Working on this now. I noticed that the ACME protocol wants a contact *URL*, typically `mailto:`. Does it make sense to have everyone supply a URL, and document that you almost certainly want a `mailto:` URL, or is it sufficiently universal to use `mailto:` even in non-LE ACME implementations that I should just have an API to supply an email address and always prefix it with `mailto:`?

**Comment by jsha** [comment]
I would recommend and API to provide an email address specifically, and if
someone later wants to provide a phone number, you can add that as well
(but it seems unlikely at this point).

**Comment by joshtriplett** [comment]
I've published tide-acme 0.1.1 with support for contact emails, and updated the examples in the documentation and `README.md` to include `.contact_email("admin@example.org")`.

I haven't made the email a hard requirement yet, since that'll be a breaking change. I'll consider making that change for tide-acme 0.2.
